### ISSUE TITLE
[BUG][FEATURE REQ] Only write maps that are selected with gamemodes

### ISSUE THREAD

**Issue by UnicornYames** [The-Nightman/ED-VotingJSON#13] opened 2023-12-17 18:25 UTC
**Is your feature request related to a problem? Please describe.**
The program writes all maps it reads from to the voting.json. This causes the server, in my case, to pair the selected gamemodes with any of those maps. Since everything that it reads it also writing to the .json.

**Describe the solution you'd like**
For the program to only write the gametypes and maps that are selected.

**Describe alternatives you've considered**
To do the selection in reverse. Instead of selecting a gamemode first, selecting a map first then the gamemodes with dropdowns for the settings for each one. So you can say select Valhalla and say, I want Slayer, CTF, and One Bomb. But it would write it as needed to be valid.

**Additional context**
N/A

**Comment by The-Nightman** [comment] 2023-12-17 21:43
Added bug label since this was unintended behavior, a fix for this will be made in the next small update but for now the workaround will be to copy the maps and variants folders into another folder and delete the gamemodes and maps you dont wish to play and then build the json or to manually remove all maps from the maps section of the json and add back the maps from each of your gamemodes in the variants section while checking for duplicates. This will be added to the known issues, as for the suggestion for selecting maps first the feasibility of this will be explored however this may significantly bloat the functions of the app and slow the process of using the app in an unfavorable manner.

**Comment by The-Nightman** [comment] 2023-12-28 05:01
This issue has been fixed in the latest release as of v1.2 and this ticket will now be closed. The feature request was explored however this brought an unnecessary amount of complication and unfortunately was deemed nonviable at this moment in time however if enough interest is shown for this feature it may be revisited in the future.

**Closed as completed by The-Nightman** 2023-12-28 05:01 UTC
Labels: bug, enhancement
